### PR TITLE
Rewrite add-on previews and image viewer page regions

### PR DESCRIPTION
**Pull request by davehunt**
Improved readability and maintainability for the test. May also help with the intermittent failure reported in #841, although I was unable to reproduce this failure locally.

### CODE REVIEW

**Comment by davehunt** [comment]
Reproduced #841 on staging [with the old test](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/73/testReport/junit/workspace.tests.desktop.test_details_page/TestDetails/test_navigation_buttons_for_image_viewer/), and the [new test passed](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/76/testReport/workspace.tests.desktop.test_details_page/TestDetails/test_image_viewer_navigation/). r? @krupa @stephendonner

**Comment by davehunt** [comment]
Full adhoc build: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/77/

**Comment by davehunt** [comment]
Adhoc build had three expected failures. 🎉

**Comment by stephendonner** [comment]
Ran this twice, reviewed the code as much as I was able, and it all looks good to me; thanks!  r+

(addon-tests) sdonners-MBP:Addon-Tests sdonner$ py.test --driver=Firefox --base-url https://addons-dev.allizom.org --servicesbaseurl https://services.addons-dev.allizom.org --variables /Users/sdonner/Desktop/AMO.json tests/desktop/

=== 3 failed, 139 passed, 13 skipped, 1 xfailed, 1 xpassed in 998.61 seconds ===

**Comment by stephendonner** [comment]
https://youtu.be/vCadcBR95oU

**Pull request merged**
