### PR TITLE
Update fxapom to 1.8.0

### PR DESCRIPTION
**Pull request by stephendonner**

### CODE REVIEW

**Comment by stephendonner** [comment]
Sorry for the pull, before I had thoroughly tested - it seems it can no longer find "mock":

```
15:32:58 [EnvInject] - Inject global passwords.
15:32:58 [EnvInject] - Mask passwords passed as build parameters.
15:32:58 Started by user Stephen Donner
15:32:58 [EnvInject] - Loading node environment variables.
15:32:58 Building in workspace /var/lib/jenkins/jobs/amo.adhoc/workspace
15:32:58 Wiping out workspace first.
15:32:58 Cloning the remote Git repository
15:32:58 Cloning repository https://github.com/stephendonner/Addon-Tests.git
15:32:58  > /usr/local/git/bin/git init /var/lib/jenkins/jobs/amo.adhoc/workspace # timeout=10
15:32:58 Fetching upstream changes from https://github.com/stephendonner/Addon-Tests.git
15:32:58  > /usr/local/git/bin/git --version # timeout=10
15:32:58 Setting http proxy: proxy.dmz.scl3.mozilla.com:3128
15:32:58  > /usr/local/git/bin/git -c core.askpass=true fetch --tags --progress https://github.com/stephendonner/Addon-Tests.git +refs/heads/*:refs/remotes/origin/*
15:33:02  > /usr/local/git/bin/git config remote.origin.url https://github.com/stephendonner/Addon-Tests.git # timeout=10
15:33:02  > /usr/local/git/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
15:33:02  > /usr/local/git/bin/git config remote.origin.url https://github.com/stephendonner/Addon-Tests.git # timeout=10
15:33:02 Fetching upstream changes from https://github.com/stephendonner/Addon-Tests.git
15:33:02 Setting http proxy: proxy.dmz.scl3.mozilla.com:3128
15:33:02  > /usr/local/git/bin/git -c core.askpass=true fetch --tags --progress https://github.com/stephendonner/Addon-Tests.git +refs/heads/*:refs/remotes/origin/*

15:33:03  > /usr/local/git/bin/git rev-parse origin/update-fxapom^{commit} # timeout=10
15:33:03 Checking out Revision 195b4ad568ce41800ca0e217702d0b3d8f7fade7 (origin/update-fxapom)
15:33:03  > /usr/local/git/bin/git config core.sparsecheckout # timeout=10
15:33:03  > /usr/local/git/bin/git checkout -f 195b4ad568ce41800ca0e217702d0b3d8f7fade7
15:33:03  > /usr/local/git/bin/git rev-list 195b4ad568ce41800ca0e217702d0b3d8f7fade7 # timeout=10
15:33:03 Run condition [Boolean condition] enabling prebuild for step [Execute shell]
15:33:03 Run condition [Not] preventing prebuild for step [Execute shell]
15:33:03 provisoning config files...
15:33:03 copy managed file [amo.json] to file:/var/lib/jenkins/jobs/amo.adhoc/workspace@tmp/config607065642002426221tmp
15:33:03 [EnvInject] - Executing scripts and injecting environment variables after the SCM step.
15:33:03 [EnvInject] - Injecting as environment variables the properties content 
15:33:03 PATH=${WORKSPACE}/.venv/bin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
15:33:03 
15:33:03 [EnvInject] - Variables injected successfully.
15:33:03 executing script 'Create virtual environment'
15:33:03 [workspace] $ /bin/bash -ex /tmp/build_step_template1618671422499036512.sh
15:33:03 + virtualenv .venv
15:33:03 New python executable in /var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/bin/python2.7
15:33:03 Also creating executable in /var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/bin/python

15:33:06 Installing setuptools, pip, wheel...done.
15:33:06 executing script 'Install infrastructure requirements'
15:33:06 [workspace] $ /bin/bash -ex /tmp/build_step_template8244974001064341400.sh
15:33:06 + pip install pytest-rerunfailures==1.0.1

15:33:06 Collecting pytest-rerunfailures==1.0.1
15:33:06 Collecting pytest>=2.7.3 (from pytest-rerunfailures==1.0.1)
15:33:06   Using cached pytest-2.9.1-py2.py3-none-any.whl
15:33:06 Collecting py>=1.4.29 (from pytest>=2.7.3->pytest-rerunfailures==1.0.1)
15:33:07   Using cached py-1.4.31-py2.py3-none-any.whl
15:33:07 Installing collected packages: py, pytest, pytest-rerunfailures
15:33:07 Successfully installed py-1.4.31 pytest-2.9.1 pytest-rerunfailures-1.0.1

15:33:07 + pip install pytest-xdist==1.8
15:33:08 Collecting pytest-xdist==1.8
15:33:08 Collecting execnet>=1.0.8 (from pytest-xdist==1.8)
15:33:08   Using cached execnet-1.4.1-py2.py3-none-any.whl
15:33:08 Requirement already satisfied (use --upgrade to upgrade): pytest>=2.2.1 in ./.venv/lib/python2.7/site-packages (from pytest-xdist==1.8)
15:33:08 Collecting apipkg>=1.4 (from execnet>=1.0.8->pytest-xdist==1.8)
15:33:08   Using cached apipkg-1.4-py2.py3-none-any.whl
15:33:08 Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in ./.venv/lib/python2.7/site-packages (from pytest>=2.2.1->pytest-xdist==1.8)
15:33:08 Installing collected packages: apipkg, execnet, pytest-xdist
15:33:08 Successfully installed apipkg-1.4 execnet-1.4.1 pytest-xdist-1.8

15:33:08 [workspace] $ /bin/sh -xe /tmp/hudson5276966045708549148.sh
15:33:08 + pip install -Ur requirements.txt
15:33:09 Collecting fxapom==1.7.2 (from -r requirements.txt (line 1))
15:33:09   Using cached fxapom-1.7.2-py2-none-any.whl
15:33:09 Collecting pyjwt==1.4.0 (from -r requirements.txt (line 2))
15:33:09   Using cached PyJWT-1.4.0-py2.py3-none-any.whl

15:33:09 Requirement already up-to-date: pytest==2.9.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
15:33:09 Collecting pytest-selenium (from -r requirements.txt (line 4))
15:33:09   Using cached pytest_selenium-1.2.1-py2-none-any.whl
15:33:09 Collecting pytest-variables (from -r requirements.txt (line 5))
15:33:09   Using cached pytest_variables-1.4-py2-none-any.whl
15:33:09 Collecting pytest-xdist==1.14 (from -r requirements.txt (line 6))
15:33:09   Using cached pytest_xdist-1.14-py2.py3-none-any.whl
15:33:09 Collecting pytz==2016.4 (from -r requirements.txt (line 7))
15:33:09   Using cached pytz-2016.4-py2.py3-none-any.whl
15:33:09 Collecting requests==2.10.0 (from -r requirements.txt (line 8))
15:33:09   Using cached requests-2.10.0-py2.py3-none-any.whl
15:33:09 Collecting PyFxA==0.1.3 (from fxapom==1.7.2->-r requirements.txt (line 1))
15:33:09   Using cached PyFxA-0.1.3-py2.py3-none-any.whl
15:33:10 Requirement already up-to-date: py>=1.4.29 in ./.venv/lib/python2.7/site-packages (from pytest==2.9.1->-r requirements.txt (line 3))
15:33:10 Collecting pytest-html>=1.7 (from pytest-selenium->-r requirements.txt (line 4))
15:33:10   Using cached pytest_html-1.8.0-py2.py3-none-any.whl
15:33:10 Collecting selenium>=2.26.0 (from pytest-selenium->-r requirements.txt (line 4))
15:33:10   Using cached selenium-2.53.2-py2.py3-none-any.whl
15:33:10 Requirement already up-to-date: execnet>=1.1 in ./.venv/lib/python2.7/site-packages (from pytest-xdist==1.14->-r requirements.txt (line 6))
15:33:10 Collecting PyOpenSSL (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
15:33:10 Collecting PyBrowserID (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Collecting pyasn1 (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached pyasn1-0.1.9-py2.py3-none-any.whl
15:33:10 Collecting six (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached six-1.10.0-py2.py3-none-any.whl
15:33:10 Collecting ndg-httpsclient (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Collecting cryptography (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Collecting hawkauthlib (from PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Requirement already up-to-date: apipkg>=1.4 in ./.venv/lib/python2.7/site-packages (from execnet>=1.1->pytest-xdist==1.14->-r requirements.txt (line 6))

15:33:10 Requirement already up-to-date: setuptools>=11.3 in ./.venv/lib/python2.7/site-packages (from cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Collecting enum34 (from cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached enum34-1.1.5-py2.py3-none-any.whl
15:33:10 Collecting ipaddress (from cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached ipaddress-1.0.16-py27-none-any.whl
15:33:10 Collecting idna>=2.0 (from cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached idna-2.1-py2.py3-none-any.whl
15:33:10 Collecting cffi>=1.4.1 (from cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10 Collecting webob (from hawkauthlib->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:10   Using cached WebOb-1.6.0-py2.py3-none-any.whl
15:33:10 Collecting pycparser (from cffi>=1.4.1->cryptography->PyFxA==0.1.3->fxapom==1.7.2->-r requirements.txt (line 1))
15:33:11 Installing collected packages: enum34, ipaddress, pyasn1, six, idna, pycparser, cffi, cryptography, PyOpenSSL, requests, PyBrowserID, ndg-httpsclient, webob, hawkauthlib, PyFxA, fxapom, pyjwt, pytest-html, pytest-variables, selenium, pytest-selenium, pytest-xdist, pytz

15:33:12   Found existing installation: pytest-xdist 1.8
15:33:12     Uninstalling pytest-xdist-1.8:
15:33:12       Successfully uninstalled pytest-xdist-1.8
15:33:12 Successfully installed PyBrowserID-0.10.0 PyFxA-0.1.3 PyOpenSSL-16.0.0 cffi-1.6.0 cryptography-1.3.2 enum34-1.1.5 fxapom-1.7.2 hawkauthlib-0.1.1 idna-2.1 ipaddress-1.0.16 ndg-httpsclient-0.4.0 pyasn1-0.1.9 pycparser-2.14 pyjwt-1.4.0 pytest-html-1.8.0 pytest-selenium-1.2.1 pytest-variables-1.4 pytest-xdist-1.14 pytz-2016.4 requests-2.10.0 selenium-2.53.2 six-1.10.0 webob-1.6.0

15:33:13 [Boolean condition] checking [true] against [^(1|y|yes|t|true|on|run)$] (origin token: ${ENV,var="SAUCE_LABS"})
15:33:13 Run condition [Boolean condition] enabling perform for step [Execute shell]
15:33:13 [workspace] $ /bin/sh -xe /tmp/hudson984356284242126540.sh
15:33:13 + py.test -n 15 --base-url https://addons-dev.allizom.org --servicesbaseurl https://services.addons-dev.allizom.org --driver SauceLabs --capability browserName Firefox --capability version 46.0 --capability platform 'Windows 7' --capability selenium-version 2.53.0 --capability build jenkins-amo.adhoc-90 --capability public 'public restricted' --variables /var/lib/jenkins/jobs/amo.adhoc/workspace@tmp/config607065642002426221tmp --html results/index.html --junitxml results/junit.xml --reruns 0 tests/desktop
15:33:13 Traceback (most recent call last):
15:33:13   File "/var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/lib/python2.7/site-packages/_pytest/config.py", line 320, in _importconftest
15:33:13     mod = conftestpath.pyimport()
15:33:13   File "/var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
15:33:13     __import__(modname)
15:33:13   File "/var/lib/jenkins/jobs/amo.adhoc/workspace/tests/conftest.py", line 8, in <module>
15:33:13     from fxapom.fxapom import DEV_URL, PROD_URL, FxATestAccount
15:33:13   File "/var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/lib/python2.7/site-packages/fxapom/fxapom.py", line 12, in <module>
15:33:13     from fxa.tests.utils import TestEmailAccount
15:33:13   File "/var/lib/jenkins/jobs/amo.adhoc/workspace/.venv/lib/python2.7/site-packages/fxa/tests/utils.py", line 24, in <module>
15:33:13     import mock  # NOQA
15:33:13 ImportError: No module named mock
15:33:13 ERROR: could not load /var/lib/jenkins/jobs/amo.adhoc/workspace/tests/conftest.py
15:33:13 
15:33:13 Build step 'Conditional step (single)' marked build as failure
15:33:13 Deleting 1 temporary files
15:33:13 Archiving artifacts
15:33:13 [htmlpublisher] Archiving HTML reports...
15:33:13 [htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/amo.adhoc/workspace/results to /var/lib/jenkins/jobs/amo.adhoc/builds/90/htmlreports/HTML_Report
15:33:13 ERROR: Specified HTML directory '/var/lib/jenkins/jobs/amo.adhoc/workspace/results' does not exist.
15:33:13 Recording test results
15:33:13 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
15:33:13 Finished: FAILURE

@davehunt sorry for the ping, but help, por favor?
```

**Comment by stephendonner** [comment]
If I understand the output, it's complaining when it tries to find https://github.com/mozilla/fxapom/blob/bc7175f5788a9144410739656943cd2e89e30915/tests/requirements.txt#L2 ?

**Comment by stephendonner** [comment]
@vladikoff in the off-chance you're around, does any of this make sense (failure) to you?

**Comment by davehunt** [comment]
If mock is required then we need to add it as a dependency somewhere. We could add it to [setup.py](https://github.com/mozilla/fxapom/blob/bc7175f5788a9144410739656943cd2e89e30915/setup.py#L25) for fxapom itself, or perhaps it makes more sense to add it as a dependency of [PyFxA](https://github.com/mozilla/PyFxA/blob/abd3b9ce282132cb30ab8378695ed4cd22cba050/setup.py#L37-L43). Coincidentally, mock is installed by the [test requirements of fxapom](https://github.com/mozilla/fxapom/blob/bc7175f5788a9144410739656943cd2e89e30915/tests/requirements.txt#L2) because we use it in these tests.

**Comment by davehunt** [comment]
@Natim could we add mock as a dependency in PyFxA as we're currently unable to use it.

**Comment by Natim** [comment]
> @Natim could we add mock as a dependency in PyFxA

Yes sure I have opened https://github.com/mozilla/PyFxA/pull/41 about it.

**Comment by davehunt** [comment]
@stephendonner we should now be able to update fxapom to use PyFxA 0.2.0, and then release fxapom 1.7.3 to allow us to upgrade.

**Comment by stephendonner** [comment]
Ad-hoc run, which passes, here: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/92/console

@davehunt r? again

**Pull request merged**
