### PR TITLE
Improve regions and tests for other add-on by the authors

### LINKED ISSUE #842: Fix test: test_navigating_to_other_addons
test_navigating_to_other_addons has been failing for a while now. My guess is that the last add-on being a theme is causing the issue but I may be wrong.

### PR DESCRIPTION
**Pull request by davehunt**
Fixes #842

### CODE REVIEW

**Comment by davehunt** [comment]
Here's an [adhoc build](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/80/).

**Comment by davehunt** [comment]
Another [adhoc](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/81) after rebasing.

**Comment by davehunt** [comment]
The adhoc only had two (familiar) failures. @stephendonner r?

**Comment by stephendonner** [comment]
LGTM!

======= 142 passed, 13 skipped, 1 xfailed, 1 xpassed in 1003.85 seconds ========

r+

**Pull request merged**
