### PR TITLE
update the DiscoveryPane class to be aware of --apibaseurl

### PR DESCRIPTION
**Pull request by m8ttyB**
For issue #745: Sorry @justinpotts, I snagged this away from you.

@stephendonner / @justinpotts r?

### CODE REVIEW

**Comment by stephendonner** [comment]
Thanks!  This LGTM (and https://saucelabs.com/jobs/0f5b59af5571452ea7469f186ad551b5); someone else feel free/encouraged to r+ and merge?

https://webqa-ci.mozilla.com/job/amo.prod.api-pull.saucelabs/ - is on our newly-public instance :-)

**Comment by stephendonner** [comment]
@davehunt / @bobsilverberg r?

**Comment by bobsilverberg** [comment]
@m8ttyB This works, and allows the test to pass, but I find it confusing. Why do we need this all of a sudden? Why was that option present in `conftest.py` but never used before? Can a comment be added into `discovery.py` to explain what we are doing and why?

**Comment by m8ttyB** [comment]
> I find it confusing. 

The solution seems a bit oddish to me too, but I was trying to avoid doing a bunch of refactoring.

> Why do we need this all of a sudden?

@stephendonner can you answer this one .. I'm not sure of the history behind why this changed on prod, the url -- why there are 2 urls that need to be used to run tests on prod

> Why was that option present in conftest.py but never used before?

I don't know the history of why this was added to `conftest.py` but not used.

> Can a comment be added into discovery.py to explain what we are doing and why?

Is the comment in the constructor unclear? I'm not sure how to amend this other than it's the `DiscoveryPane` class is initialized to use.

**Comment by bobsilverberg** [comment]
@m8ttyB For the comment I meant adding a comment explaining why we need to use the api_base_url if passed. The current comment doesn't explain the why, just that we need to use it if passed.

If the answer to this is that nobody really knows, then that's a bit scary.

**Comment by m8ttyB** [comment]
@bobsilverberg

**Comment by stephendonner** [comment]
Here's the scoop from @jasonthomas "the web workers use the same config as addons.mozilla.org workers but we heavily restrict what can be served from SAMO https://github.com/mozilla-services/svcops-puppet/blob/dev/modules/marketplace/templates/nginx/services_addons.conf"

And from Krupa: "disco pane is accessed from within the browser, so it needs to be a separate domain for security and performance reasons."

**Comment by m8ttyB** [comment]
@stephendonner would it make sense to rename `--apibaseurl` to something more meaningful? Suggestions?

**Comment by stephendonner** [comment]
I think that perhaps "servicesbaseurl" might make the most sense, given that it describes the use of the flag quite aptly.

**Comment by stephendonner** [comment]
Thx; the comments/notes and the param change LGTM -- tested in public Jenkins and carrying-forward the r+.

**Comment by davehunt** [comment]
`--apibaseurl` was used by https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_api_only.py and https://github.com/mozilla/Addon-Tests/blob/master/pages/desktop/addons_api.py but it looks like this was changed (perhaps unintentionally) in https://github.com/mozilla/Addon-Tests/commit/76f85a0558c554c851639bff0f13f7d41f031553 to use the base URL.

**Comment by davehunt** [comment]
@m8ttyB, @stephendonner, @bobsilverberg see my comment above. The command line argument was appropriate and originally used for testing the API. The fact that we're not using this currently for the API tests may be a regression we need to fix. FWIW it didn't take much digging to find this information in the commit history.

**Pull request merged**
