### PR TITLE
Upgrade pytest dependencies

### PR DESCRIPTION
**Pull request by davehunt**
Tested locally against dev on Mac OS X 10.10.2

### CODE REVIEW

**Comment by m8ttyB** [comment]
Woot woot .. thanks @davehunt !

**Comment by bobsilverberg** [comment]
@davehunt @m8ttyB I see this is already merged, but I was wondering, isn't `pytest-xdist` currently covered via our standard infrastructure requirements? It looks like not all of the suites are using those instead of explicitly listing the packages in `requirements.txt`, but we should probably remedy that as we work on the files.

Is there a reason to keep it in this file, rather than installing it via the infrastructure requirements?

**Comment by davehunt** [comment]
@bobsilverberg the infrastructure requirements installs a specific version of pytest-xdist, and not the latest. While I suspect the latest version should be backwards compatible, I decided to stick to the in-tree requirements here. The plugin is not actually required for running any of our tests (it's just handy, for running in parallel). For what it's worth, a pinned version in the repo would take priority over the infra requirements as it's installed last.

**Comment by davehunt** [comment]
hmm.. actually it is assumed to be present by the Travis build, so I think it's worth keeping it in the repo.

**Comment by bobsilverberg** [comment]
@davehunt if that's the case then is there any reason to keep it as part of the infrastructure requirements? I find this confusing. I don't see a point in having something in the infrastructure requirements if we are also going to specify it in the `requirements.txt`. Also, why does Travis assume it to be present when all Travis is doing is running `flake8` tests?

**Comment by davehunt** [comment]
@bobsilverberg it's needed for any repos that don't have it explicitly set as a requirement. Our CI requires parallel test execution. Travis in this repository is not just running flake8.

**Pull request merged**
