### PR TITLE
Fix mobile test_sort_by_region failure

### PR DESCRIPTION
**Pull request by AndreiH**
This is for https://github.com/mozilla/Addon-Tests/issues/738

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks for this, @AndreiH. It seems like a good fix for `test_sort_by_region`, but it is now causing `TestHome.test_all_featured_extensions_link` to fail. See below:

```
 tests/mobile/test_home.py:74: TestHome.test_all_featured_extensions_link FAILED

================================================================= FAILURES ==================================================================
________________________________________________ TestHome.test_all_featured_extensions_link _________________________________________________

self = <tests.mobile.test_home.TestHome instance at 0x101b0f680>
mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x101b0f8c0>

    @pytest.mark.nondestructive
    def test_all_featured_extensions_link(self, mozwebqa):

        home = Home(mozwebqa)
        Assert.true(home.is_the_current_page)
        Assert.equal(home.default_selected_tab_text, 'Featured')

        home.scroll_down  # workaround for selenium scroll issue

>       featured_extensions = home.click_all_featured_addons_link()

tests/mobile/test_home.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.mobile.home.Home object at 0x101b0ddd0>

    def click_all_featured_addons_link(self):
        self.scroll_to_element(*self._all_featured_addons_locator)
        self.selenium.find_element(*self._all_featured_addons_locator).click()
        from pages.mobile.extensions import Extensions
        extensions_page = Extensions(self.testsetup)
>       WebDriverWait(self.selenium, self.timeout).until(lambda s: self.is_element_visible(*extensions_page._sort_by_locator))

pages/mobile/home.py:92:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.support.wait.WebDriverWait object at 0x101b0ded0>, method = <function <lambda> at 0x1044c8398>, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        end_time = time.time() + self._timeout
        while(True):
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions:
                pass
            time.sleep(self._poll)
            if(time.time() > end_time):
                break
>       raise TimeoutException(message)
E       TimeoutException: Message:

../../.virtualenvs/Addon-Tests/lib/python2.7/site-packages/selenium/webdriver/support/wait.py:71: TimeoutException
-------------------------------------------------------------- pytest-mozwebqa --------------------------------------------------------------
Failing URL: https://addons-dev.allizom.org/en-US/firefox/
---------------------------------- generated xml file: /Users/bsilverberg/gitRepos/Addon-Tests/results.xml ----------------------------------
======================================= 13 tests deselected by '-ktest_all_featured_extensions_link' ========================================
================================================= 1 failed, 13 deselected in 113.70 seconds =================================================
```

**Comment by AndreiH** [comment]
Thanks for showing me this @bobsilverberg 
The reason that was failing is because it also had a <code>scroll_down</code> method that I just removed.
Please see adhoc here with all the runs: http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.prod.mobile.saucelabs.andreih/

**Comment by bobsilverberg** [comment]
It works well now @AndreiH. Thanks for this fix! Hopefully this will address issue #738 which @stephendonner reported.

**Comment by bobsilverberg** [comment]
r+ Please squash the commits

**Pull request merged**
