### PR TITLE
Switch to Firefox Accounts on dev

### PR DESCRIPTION
**Pull request by davehunt**
This addresses #800 but includes an ugly workaround for https://github.com/mozilla/olympia/issues/1551. We _could_ merge this, and it should fix the failures in Jenkins, but I'd prefer to wait on a fix that avoids the workaround.

@bobsilverberg would you mind reviewing this? If @krupa is fine with the workaround we can merge this to fix the failures.

### CODE REVIEW

**Comment by davehunt** [comment]
Adhoc:
* Dev: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/13/
* Stage: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/14/

**Comment by bobsilverberg** [comment]
This looks good @davehunt. I agree it isn't ideal, but I think it's a nice way of dealing with the issue for now. Just a comment, I noticed when running the tests that we have some inefficient waits (particularly when waiting to be logged out) which cause the tests to pause unnecessarily. You may want to address those in a separate PR.

r+

**Comment by davehunt** [comment]
I've updated this now that FxA is enabled for both staging and dev. This means that any login tests run against production would fail, however now that we create users as needed, these tests are considered destructive and will be skipped in prod by default. Unfortunately dev and staging are having issues at the moment, so although this will reduce the number of failures, it will not make the builds go green.

Also note that this is a temporary workaround until mozilla/addons-server#1551 is resolved.

@stephendonner r?

**Comment by stephendonner** [comment]
Carrying over Bob's r+, and took a look at this as well.  

1) As you say, this will reduce the # of failures (from 20, currently on both dev/stage), to around 11 or 12, with this patch.
2) Additionally, some of those I've seen on recent ad-hoc runs are our favorite "Squix-proxy timeouts..." bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1238977)
3) There's a Django 1.8 upgrade happening next week on AMO, so we should get this in to restore test-automation coverage as much as possible, not merely for, but especially for, that big upgrade.
4) Having this in will give us a cleaner working state to shore up reliable coverage, so merging away!

**Pull request merged**
