### PR TITLE
cleaned the repo using flake8

### PR DESCRIPTION
**Pull request by tessie**
'

### CODE REVIEW

**Comment by m8ttyB** [comment]
r+ -- thank you @tessie for adding the `import` -- @bobsilverberg shall we merge?

**Comment by stephendonner** [comment]
Do we still need this, given https://github.com/mozilla/Addon-Tests/pull/750 ?

**Comment by m8ttyB** [comment]
@tessie Thank you for your work! Your pull request has precedence over some work that I merged yesterday -- I apologize, I didn't see your pr. I'll take the task of resolving the merge conflicts if it appears that we can still use this pr.

**Comment by m8ttyB** [comment]
I'm going to close this pr but will integrate your work.

**Comment by tessie** [comment]
@m8ttyB .Its ok

**Pull request closed without merging**
