### PR TITLE
Create users and log in via the API using a session cookie

### PR DESCRIPTION
**Pull request by davehunt**
This patch uses the new super-create API endpoint to create a user with an associated Firefox Account and then logs in using a cookie instead of using the UI. One test is left to use the UI to ensure we have coverage of that area.

@krupa, @stephendonner ,@rbillings: r?

### CODE REVIEW

**Comment by davehunt** [comment]
A quick check shows that this saves ~35 seconds for a test that requires login. There are ~13 tests affected, so this could save us over 7 minutes each time we run these tests.

**Comment by kumar303** [comment]
@davehunt should be added now. Let me know if it doesn't work.

**Comment by davehunt** [comment]
> @davehunt should be added now. Let me know if it doesn't work.

@kumar303 I'm getting a 404 on staging, has the new endpoint been deployed yet?

**Comment by krupa** [comment]
This makes me super happy! Thanks @davehunt and @kumar303 for making this happen.

**Comment by krupa** [comment]
This makes me super happy! Thanks @davehunt and @kumar303 for making this happen.

**Comment by davehunt** [comment]
Updated to use the display name from the created user. This is ready to merge once it gets an r+ but there will be two tests failing on staging until a deployment is made with the most recent API changes.

**Comment by davehunt** [comment]
@stephendonner or @rbillings do you have time for a review?

**Comment by rbillings** [comment]
Changes look good. All tests pass locally except for test_discovery_page which has a timeout [https://public.etherpad-mozilla.org/p/OZPAJSFphU], which I'm not sure is related to these changes. R+ with comment.

**Pull request merged**
