### PR TITLE
Fix locator following mozilla/olympia#720

### LINKED ISSUE #790: Fix test_reviews.TestReviews	test_that_new_review_is_saved failure
test_reviews.TestReviews test_that_new_review_is_saved began failing* after this commit:

https://github.com/mozilla/olympia/commit/a43d0c4c9431c8122a13c909ab512b6719d20496

*https://webqa-ci.mozilla.com/job/amo.dev.saucelabs/512/

Issue does not repro manually, and the id_body locator has not changed however re-running the build prompts further failures.

### PR DESCRIPTION
**Pull request by davehunt**
Fixes #790

### CODE REVIEW

**Comment by davehunt** [comment]
Adhoc: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/36/

**Comment by rbillings** [comment]
LGTM, tests pass locally. +1

**Comment by davehunt** [comment]
> PASSED test_reviews.py::TestReviews::test_that_new_review_is_saved

There was one unrelated failure. I'm rerunning to see if this an intermittent: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/37/

**Comment by davehunt** [comment]
More failures, but they don't appear to be related. Noted that our adhoc jobs do not automatically rerun failures, so they will likely appear to be more brittle.

**Pull request merged**
