### PR TITLE
Fix issue #859

### PR DESCRIPTION
**Pull request by justinpotts**

### CODE REVIEW

**Comment by m8ttyB** [comment]
r+ 
mango

**Comment by stephendonner** [comment]
@justinpotts probably a good idea to remove the page object(s) too, right?  https://github.com/mozilla/Addon-Tests/blob/e72973b5571cdd6d33b9f13f4cb5bf0d9116723f/pages/desktop/discovery.py at least; there might be more (and perhaps methods, elsewhere?)

**Comment by justinpotts** [comment]
@stephendonner, you're right. Didn't think of that!

**Comment by justinpotts** [comment]
@stephendonner r+?

**Comment by stephendonner** [comment]
Thx; looks like that's all disco* stuff gone, to me.  r+

**Pull request merged**
