### PR TITLE
Update requirements and add badge to README

### PR DESCRIPTION
**Pull request by davehunt**
Adhoc jobs:
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/46/
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.mobile.adhoc/11/

Pinging @mozilla/web-qa-sorcerers for review.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
The code changes look fine. The desktop adhoc, however, shows 3 failures. I doubt they are related, but it's something to at least look at.

**Comment by davehunt** [comment]
I saw that too, a rerun had a single failure. It looks like it may be a connection issue with Sauce Labs. I doubt it's related to this change.

**Comment by bobsilverberg** [comment]
Agreed. r+

**Comment by rbillings** [comment]
LGTM

**Pull request merged**
