### PR TITLE
Add -n=10 for concurrency

### PR DESCRIPTION
**Pull request by stephendonner**
Currently, amo.adhoc builds on fx-test-jenkins-dev.stage take ~50-60 minutes[0], since they (for whatever reason, which @davehunt probably knows) don't take advantage of pytest-xdist/concurrency.

Even without this PR's change, on https://fx-test-jenkins.stage.mozaws.net, jobs range from ~6-9 minutes, since they are able to run many tests concurrently.

This proposed change is in line with fxapom: https://github.com/mozilla/fxapom/blob/30342cb41a928c8912fe4c7cf43e436a63715c01/Jenkinsfile#L20 and socorro: https://github.com/mozilla-services/socorro/blob/0dd2f213b73c10a1e7a4bcc309e461f4d35dc84d/e2e-tests/Jenkinsfile#L19.

Ad-hoc run with change = ~ 8 minutes: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/amo.adhoc/78/

[0] https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/amo.adhoc/77/

### CODE REVIEW

**Comment by davehunt** [comment]
I noticed this yesterday too. Rather than force 10 concurrent processes, I'd rather investigate why auto isn't running across multiple processes. Has anything changed in our infrastructure? There have been a few pytest-xdist releases recently, so could this be a regression? Is this also affecting prod?

**Comment by stephendonner** [comment]
This isn't affecting prod, and I haven't been able to yet find a regression range, sorry.  I'll try to take a closer look today, when I get in to the office.

**Comment by davehunt** [comment]
This issue might go away when we switch to a new Jenkins instance, however what appears to be happening here is that `from multiprocessing import cpu_count; cpu_count()` is returning `1`. I'm not sure what the differences are between our production and staging instances, but for some reason they're reporting a different number of CPU cores.

Rather than hard-code a value, I'd rather find a way to override just for the environments where it's needed. We did that previously with a `PYTEST_PROCESSES` environment variable before we switched to declarative pipelines.

**Comment by stephendonner** [comment]
Hey @davehunt!  Good news; I finally dug into this, today, and here's what I found (and it seems to make sense, now):

AWS EC2 Instance Types for our Jenkins prod (master, slave) and Jenkins dev (master, slave) are as follows, respectively.

1) Prod
    a) Master: m4.2xlarge, 8 vCPUs (not sure how many cores, though?)
    b) Slave: m4.2xlarge, 8 vCPUs
2) Dev
    a) Master: m3.medium, 1 vCPU
    b) Slave: m3.medium, 1 vCPU

As you'd expect, then, we should anticipate that ```from multiprocessing import cpu_count; cpu_count()``` on both/either of Jenkins master/slave for prod returns "8," while -- as you discovered already -- for either/both Jenkins master/slave for dev, it returns 1.

You can see these in the screenshot, below - just look for the green (i.e. active instances) balls (I'm too lazy to go back to the login and sort and re-grab the screenshot).

screen shot 2017-07-25 at 12 59 54 pm

So, this looks legit, and while I'll push for a large instance type for more capacity in our new setup, I'm a +1 for adding this change back in, now that I think I/we understand it better?

**Comment by davehunt** [comment]
> I'm a +1 for adding this change back in

If by this you mean hard-coding to 10 processes, I'm still -1. What I'd like is to use `auto` unless an environment variable is set on the instance to override it. Then we could override it based on the individual instances. At the moment I'm not sure if this is possible in declarative pipelines, but I have mentioned it to :abayer, and he thought it to be a reasonable feature request. I'll raise a ticket now.

**Comment by davehunt** [comment]
I've raised [JENKINS-45991](https://issues.jenkins-ci.org/browse/JENKINS-45991).

**Comment by stephendonner** [comment]
Yeah, meant n=10.  OK, thanks - we'll revisit this when https://issues.jenkins-ci.org/browse/JENKINS-45991 (fixed, not-yet-released) and https://issues.jenkins-ci.org/browse/JENKINS-42753 (not-yet-fixed) are available for our use.

**Pull request closed without merging**
