### PR TITLE
Remove pagination from add-on island page region object

### LINKED ISSUE #843: fix test: test_that_checks_the_up_and_coming_extensions_island
test_that_checks_the_up_and_coming_extensions_island is failing because for some reason the test is loading the devhub landing page. My guess that we are not waiting sufficiently long enough for the page to load and the wrong element is being clicked.

### PR DESCRIPTION
**Pull request by davehunt**
Also removed other unused code from the test and page region objects. Fixes #843 

@krupa @stephendonner r?

### CODE REVIEW

**Comment by davehunt** [comment]
Hold off on this one for now.. there are 18 add-ons found by the test. This means that although the pagination has been removed in the redesign, the 'pages' are still in the DOM.

**Comment by davehunt** [comment]
I've now updated to just check the first 'page' of add-ons.

**Comment by davehunt** [comment]
It appears that the add-on islands no longer have the pagination, but the additional add-ons are still in the HTML. @tofumatt suggested pinging @designakt and @pwalm to check that this is intentional.

Before (with pagination):

screenshot 2016-04-19 16 30 49

After (without pagination):

screenshot 2016-04-19 16 31 21

**Comment by pwalm** [comment]
Yep, kill the pagination. We don't need 3-5 carousels on the front page. Click through on those are abysmal anyway.

**Comment by davehunt** [comment]
@pwalm thanks - should we raise a bug against the front-end to remove the additional pages from the DOM? It could have a positive impact on performance too.

**Comment by pwalm** [comment]
Yes, let's.

**Comment by davehunt** [comment]
Here's an [ad-hoc build](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/79/) with the [test passing](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/79/testReport/tests.desktop.test_homepage/TestHome/test_up_and_coming_extensions/) and only expected failures.

**Comment by davehunt** [comment]
Raised https://github.com/mozilla/addons-server/issues/2436 to remove the additional add-ons from the front end.

**Comment by stephendonner** [comment]
Thanks; r+ - only failure was the unrelated TestDetails.test_navigating_to_other_addons failure.  We're getting so close; awesome work!

**Pull request merged**
