### PR TITLE
Switch to native asserts. Fixes #776

### LINKED ISSUE #776: Switch to native asserts
We have decided to move away from [unittest-zero](https://github.com/AutomatedTester/unittest-zero unittest-zero) and switch our assertions to be native asserts. This is [best practice for py.test](http://pytest.org/latest/assert.html#asserting-with-the-assert-statement) and generally provides better failure messages.

This involves removing the unittestzero dependency, and changing every use of it to a native assert:

```python
from unittestzero import Assert
Assert.equal(actual, expected)
Assert.true(boolean)
```

would become:

```python
assert actual == expected
assert boolean
```

custom failure messages can be added with a comma separating them from the assert:

```python
assert actual == expected, 'value is not correct'
```

For an example of a switch to native asserts, see this commit: https://github.com/mozilla/mozwebqa-examples/commit/36c47336ed5d3a913fec54563f3322eb174163d2

Take special care when writing or reviewing these patches that we maintain the original intention of the assertion (unless we get confirmation that the original assertion is incorrect). There may be some advanced use cases that we will need to address. If you are unsure, please let us know via a comment on this issue.

### PR DESCRIPTION
**Pull request by davehunt**
Replaces previous pull requests #777 and #779.

 * Adhoc desktop: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.adhoc/34/
 * Adhoc mobile: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.mobile.adhoc/8/

Pinging @bobsilverberg or @m8ttyB for review.

### CODE REVIEW

**Comment by rbillings** [comment]
Changes look good to me. All desktop tests pass. Mobile tests fail, but for unrelated reasons such as locators.

**Comment by davehunt** [comment]
Which mobile tests failed? They all passed for me in the adhoc run.

**Comment by davehunt** [comment]
Ah, my adhoc didn't include destructive tests. Running again with `--destructive`.

**Comment by davehunt** [comment]
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/amo.mobile.adhoc/9/

**Comment by rbillings** [comment]
I haven't run these tests in so long I feel confident that it's something related to my repo.

**Comment by davehunt** [comment]
Thanks for the review @rbillings :smile:

**Pull request merged**
